// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ZTPWordsProject.DatabaseModels;

namespace ZTPWordsProject.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20211228124156_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("ZTPWordsProject.DatabaseModels.Translation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Translations");
                });

            modelBuilder.Entity("ZTPWordsProject.DatabaseModels.Word", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Language")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Words");
                });

            modelBuilder.Entity("ZTPWordsProject.DatabaseModels.WordTranslation", b =>
                {
                    b.Property<int>("TranslationId")
                        .HasColumnType("int");

                    b.Property<int>("WordId")
                        .HasColumnType("int");

                    b.HasKey("TranslationId", "WordId");

                    b.HasIndex("WordId");

                    b.ToTable("WordTranslations");
                });

            modelBuilder.Entity("ZTPWordsProject.DatabaseModels.WordTranslation", b =>
                {
                    b.HasOne("ZTPWordsProject.DatabaseModels.Translation", "Translation")
                        .WithMany("WordTranslations")
                        .HasForeignKey("TranslationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ZTPWordsProject.DatabaseModels.Word", "Word")
                        .WithMany("WordTranslations")
                        .HasForeignKey("WordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Translation");

                    b.Navigation("Word");
                });

            modelBuilder.Entity("ZTPWordsProject.DatabaseModels.Translation", b =>
                {
                    b.Navigation("WordTranslations");
                });

            modelBuilder.Entity("ZTPWordsProject.DatabaseModels.Word", b =>
                {
                    b.Navigation("WordTranslations");
                });
#pragma warning restore 612, 618
        }
    }
}
